name: Python tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check for python file changes
        uses: getsentry/paths-filter@v2
        id: changes
        with:
          filters: |
            python-files:
              - '**/*.py'
              - 'Pipfile'
              - 'Pipfile.lock'

      - name: Install Python
        uses: actions/setup-python@v1
        if: steps.changes.outputs.src == 'true'
        with:
          python-version: 3.9
      - name: Install dependencies
        if: steps.changes.outputs.src == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv lock --dev --keep-outdated --requirements > requirements.txt
          rm Pipfile Pipfile.lock
          pip install --upgrade --no-cache-dir -r requirements.txt
      - name: Run tests
        if: steps.changes.outputs.src == 'true'
        run: python -m unittest
      - name: Run linter
        if: steps.changes.outputs.src == 'true'
        run: flake8
